# Generated by Django 5.1.6 on 2025-02-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_created_at_message_sent_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ContactMessage',
        ),
    ]
